
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
# temp file 
name: Go Green

on:
  pull_request:
    branches:
      - development
      - master
      - staged
    tags:
      - '*'

env:
  ## Sets environment variable  
  tag: 0
  commit: 0


jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: wagoid/commitlint-github-action@v4
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

    notification:
      always()
      needs: commitlint
      runs-on: ubuntu-latest
      steps:
        - name: run ouput
          run: |
            echo ${{needs.commitlint}}
        - name: Slack Notification
          if: failure()
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: general
            SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
            SLACK_MESSAGE: 'Webapp: UMS (Development) deployment has been failed.'
            SLACK_TITLE: Message
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}