
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
# temp file 
name: Validation

on:
  pull_request:
    branches:
      - development
      - master
      - staged
    tags:
      - '*'

env:
  ## Sets environment variable  
  tag: 0
  commit: 0


jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      # Run the commitlint action, considering its own dependencies and yours as well 🚀
      # `github.workspace` is the path to your repository.
      - uses: wagoid/commitlint-github-action@v4
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules